# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'clean-panamera-ios' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for clean-panamera-ios
  pod 'Alamofire', '~> 4.4.0'
  pod 'AlamofireImage', '~> 3.2.0'
  pod 'AlamofireNetworkActivityIndicator', '~> 2.1.0'
  pod "DequeuableRegistrable", :git => "https://github.com/fmo91/DequeuableRegistrable/"

  target 'clean-panamera-iosTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'clean-panamera-iosUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
